format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[username]
show_always = true
format = '[$user]($style)[@](italic bright-black)'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style) '
style = 'bold bright-green'

[line_break]
disabled = true

[directory]
style = "purple"

[character]
success_symbol = "[\\$](cyan)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[\\$](green)"

[git_branch]
format = "[$symbol$branch]($style) "
style = "#769ff0"

[git_status]
#format = "[*$conflicted$deleted$renamed$modified$staged$untracked](128) [$ahead_behind$stashed]($style)"
format = '[\[[$all_status](197)[$ahead_behind](213)\]]($style) '
staged = '[+$count](green)'
stashed = "≡"
modified = "*"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

